#!/bin/bash

# Checking for dialog availability
dialogPresent=`which dialog`
if [ "X$dialogPresent" == "X" ]
then
        echo "Installing dialog using..."
        apt-get install dialog -y > /dev/null
        exit 1
fi

cmd=(dialog --separate-output --checklist "Select options:With Root user only" 22 76 16)
options=(1 "Spark" off    # any option can be set to default to "on"
         2 "DBever" off
         3 "Filezilla" off
         4 "Sublime" off
         5 "Eclipse" off
         6 "Visual Studio" off
         7 "Android Studio" off
         8 "X Forwording" off
         9 "Bomgar" off
         10 "Jmeter" off
         11 "WPS Office" off)
choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
clear
echo "Updating the system"
apt-get update -y > /dev/null
echo "------------System is updated---------------"
for choice in $choices
do
    case $choice in
        1)
                echo "------------Spark---------------------------"
                echo "------------Installing JRE------------------"
                apt-get install default-jre -y > /dev/null
                wget -q http://www.igniterealtime.org/downloadServlet?filename=spark/spark_2_8_3.deb
                echo "------------Installing Spark----------------"
                dpkg -i *spark*.deb  > /dev/null
                rm -rf *spark*.deb
                cd /usr/share/spark
                wget -q http://www.thefanclub.co.za/sites/default/files/images/howto/logo-spark_256x256.png
                echo "------------Creating Application------------"
                sudo echo "[Desktop Entry]

                Name=Spark
                Version=2.8.2
                GenericName=Spark
                X-GNOME-FullName=Spark
                Comment=ignite realtime Spark IM client
                Type=Application
                Categories=Application;Utility;
                Path=/usr/share/spark/bin
                Exec=spark
                Terminal=false
                StartupNotify=true
                Icon=/usr/share/spark/logo-spark_256x256.png
                TargetEnvironment=Unity" >> /usr/share/applications/spark.desktop
                echo "------------Done----------------------------"
            ;;
        2)
                echo "------------DBever--------------------------"
                echo "------------Installing----------------------"
				echo "will take time depends on speed of the internet"
                wget -q https://dbeaver.jkiss.org/files/dbeaver-ce_latest_amd64.deb
                dpkg -i dbeaver-ce_latest_amd64.deb  > /dev/null
                echo "------------Done----------------------------"
                rm -rf dbeaver*.deb
            ;;
        3)
                echo "------------Filezilla-----------------------"
                echo "------------Installing----------------------"
                apt install filezilla -y  > /dev/null
                echo "------------Done----------------------------"
            ;;
        4)
				echo "------------Sublime-------------------------"
                echo "------------Installing ------------"
                wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
                echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
                apt-get update -y  > /dev/null
                apt-get install sublime-text -y  > /dev/null
                echo "------------Done----------------------------"
            ;;
        5)
				echo "------------Eclipse-------------------------"
                echo "------------Downloading---------------------"
				echo "will take time depends on speed of the internet"
                wget -q http://ftp.yz.yamagata-u.ac.jp/pub/eclipse/technology/epp/downloads/release/neon/R/eclipse-jee-neon-R-linux-gtk-x86_64.tar.gz
                tar xvf eclipse-jee-neon-R-linux-gtk-x86_64.tar.gz  > /dev/null
                mv eclipse /opt
                echo "------------Creating Application------------"
                echo "[Desktop Entry]

                Name=Eclipse
                Type=Application
                Exec=/opt/eclipse/eclipse
                Terminal=false
                Icon=/opt/eclipse/icon.xpm
                Comment=Integrated Development Environment
                NoDisplay=false
                Categories=Development;IDE;" >> /usr/share/applications/eclipse.desktop
                echo "------------Done----------------------------"
				rm eclipse*.tar.gz
            ;;
        6)
				echo "------------Visual Studio-------------------"
                echo "------------Downloading---------------------"
				echo "will take time depends on speed of the internet"
                wget -q https://az764295.vo.msecnd.net/stable/79b44aa704ce542d8ca4a3cc44cfca566e7720f1/code_1.21.1-1521038896_amd64.deb
                echo "------------Installing----------------------"
                dpkg -i code_*.deb  > /dev/null
                echo "------------Done----------------------------"
                rm -rf code_*.deb
            ;;
        7)
				echo "------------Android Studio------------------"
                echo "------------Installing----------------------"
				echo "will take time depends on speed of the internet"
                apt install -y gcc-multilib g++-multilib libc6-dev-i386 qemu-kvm mesa-utils  > /dev/null
                wget -q https://dl.google.com/dl/android/studio/ide-zips/3.1.0.16/android-studio-ide-173.4670197-linux.zip
                apt-get install unzip -y > /dev/null
                unzip android-studio*.zip -d /opt > /dev/null
                echo "------------Creating Application------------"
                sudo echo "[Desktop Entry]

				Name=Android Studio
                Version=2.2.2
                GenericName=Android Studio
                X-GNOME-FullName=Android Studio
                Type=Application
                Categories=Application;Utility;
                Path=/opt/android-studio/bin/
                Exec=studio.sh
                Terminal=false
                StartupNotify=true
                Icon=/opt/android-studio/bin/studio.png
                TargetEnvironment=Unity" >> /usr/share/applications/androidstudio.desktop
                echo "------------Done----------------------------"
				rm android-studio*.zip
            ;;
        8)
				echo "------------X-Forwording--------------------"
                apt-get install python python-tk -y
				echo "------------Enter the Password to copy------"
                sudo rsync -r user@192.168.104.11:/opt/python /opt/
                cp /etc/profile /etc/profile-vs-bk
                echo "/opt/python/test.sh" >> /etc/profile
                echo "------------Done----------------------------"
            ;;
        9)
                echo "------------Bomgar--------------------------"
				echo "------------Enter the Password to copy------"
                rsync -r user@192.168.104.11:/opt/python/bomgarapk/bomgar-acc-installer.desktop /opt/python/
				echo "------------Done----------------------------"

            ;;

        10)
				echo "------------J-Meter-------------------------"
				echo "------------Installing----------------------"
				echo "will take time depends on speed of the internet"
                wget -q http://redrockdigimark.com/apachemirror//jmeter/binaries/apache-jmeter-4.0.tgz
                tar -xf apache-jmeter*.tgz > /dev/null
                mv apache-jmeter-4.0 /opt > /dev/null
				rm apache-jmeter*.tgz
				echo "------------Done----------------------------"
            ;;
        11)
				echo "------------WPS-----------------------------"
				echo "------------Installing----------------------"
				echo "will take time depends on speed of the internet"
				wget -qO wps-office.deb http://kdl.cc.ksosoft.com/wps-community/download/a21/wps-office_10.1.0.5672~a21_amd64.deb
                dpkg -i wps-office*.deb > /dev/null
                apt-get -f install && rm wps-office*.deb
                wget -qO web-office-fonts.deb http://kdl.cc.ksosoft.com/wps-community/download/fonts/wps-office-fonts_1.0_all.deb
                dpkg -i web-office-fonts.deb > /dev/null
				rm web-office-fonts.deb
				echo "------------Done----------------------------"
           ;;
    esac
done
         
